# Generated by Django 4.1.6 on 2023-03-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='repo_link',
            field=models.CharField(default='#', max_length=150, null=True),
        ),
    ]
